spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://172.20.10.15:1500"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: cas-service
          uri: lb://CAS-SERVICE
          predicates:
            - Path=/ase-user/**,/auth,/auth/csrf

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/box/**,/delivery/**,/user/**
        # TODO:Configure routes to access project services

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

server:
  port: ${PORT:10789}
