spring:
  application:
    name: cas-service
  data:
    mongodb:
      uri: mongodb+srv://ase:team11@ase-delivery-shared-db.unatfkw.mongodb.net/?retryWrites=true&w=majority
      database: authentication
      auto-index-creation: true
      repositories:
        enabled: true
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: wanzhu98@gmail.com
    password: azcscyeafbvrajeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${PORT:8081}

